### ISSUE TITLE
Mach-O: symbol size is always 0

### ISSUE THREAD

**Issue by jedisct1** [gimli-rs/object#114]
Hi!

And thanks a ton for this amazing crate.

Not sure if I did something wrong, if this is intentional, if this is a bug or simply something that hasn't been implemented, but when loading a Mach-O library, symbols have a correct address but their size is always `0`.

This happens no matter what the symbol kind is. With an ELF library, the correct size is returned and `symbol_data()` works as expected.

**Comment by philipc** [comment]
The Mach-O file format doesn't include sizes for symbols. It's possible to guess the size, and we do this [in the `symbol_map` function](https://github.com/gimli-rs/object/blob/aced06a20eb59867c88e23c03e15613ffd582618/src/read/macho.rs#L150). I've been reluctant to do this because it requires sorting the symbols within sections, and symbol iteration and `symbol_by_index` are both meant to be relatively cheap. But it's unfortunate that this means `symbol_data()` is unusable for it. Maybe we should try to do better.

Also, note that Mach-O symbols currently always have [`SymbolKind::Unknown`](https://github.com/gimli-rs/object/blob/aced06a20eb59867c88e23c03e15613ffd582618/src/read/macho.rs#L435). That's something that we should be able to do better for.

**Comment by jedisct1** [comment]
This is indeed a potentially expensive operation. But having functions that are part of the `object` abstraction layer that behave differently according to the library format defeats a little bit the purpose of that abstraction.

Could an optional `Object` method that precomputes the sizes, so that `symbol_data()` works consistently be an option?

**Comment by philipc** [comment]
> Could an optional Object method that precomputes the sizes, so that symbol_data() works consistently be an option?

That sounds reasonable to me.

**Comment by philipc** [comment]
Another option is to call `symbol_map` instead and use the symbols from it.

**Comment by philipc** [comment]
I think I prefer the `symbol_map` solution. Let me know if that doesn't solve your problem. You may need #116 as well in order for `symbol_map` to filter the symbols correctly. If this is filtering out too many symbols still then maybe we can add something to customize that.

**Comment by jedisct1** [comment]
`symbol_map` is fine, thanks!

What I needed is retrieve the offset of a symbol. Because this requires information from the section header, I had to resort to using the low level Goblin's functions, and treat Elf and Mach-O differently anyway.
