### ISSUE TITLE
patch possibly broke cargo-bloat on macs

### ISSUE THREAD

**Issue by erickt** [gimli-rs/object#115]
cargo-bloat wasn't working for me on my mac (https://github.com/RazrFalcon/cargo-bloat/issues/35), and I bisected the bug down to this patch in the object library: c600365c7c28ded74b1539ef2a7813e726e06a3e. I patched goblin to point at a fork of object, and saw it outputs data before that patch, but not afterwards. With the patch:

```
% cargo run bloat --crates -n 2
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/cargo-bloat bloat --crates -n 2`
Compiling ...
Analyzing target/debug/cargo-bloat

File  .text Size Name
0.0% 100.0%   0B .text section size, the file size is 13.2MiB

Note: numbers above are a result of guesswork. They are not 100% correct and never will be.
```

Without:

```
% cargo run bloat --crates -n 2
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/cargo-bloat bloat --crates -n 2`
Compiling ...
Analyzing target/debug/cargo-bloat

 File  .text   Size Name
12.8%  31.1% 1.7MiB std
 7.6%  18.4% 1.0MiB clap
41.1% 100.0% 5.4MiB .text section size, the file size is 13.2MiB

Note: numbers above are a result of guesswork. They are not 100% correct and never will be.
```

I'm not familiar with how these tools work, so I'm not sure if this is a bug in cargo-bloat or object. Do you know what's going on?

**Comment by philipc** [comment]
It's because cargo-bloat only considers symbols that are `SymbolKind::Text`, but Mach-O symbols currently are always `SymbolKind::Unknown` (and this was changed in https://github.com/gimli-rs/object/commit/c600365c7c28ded74b1539ef2a7813e726e06a3e).

So this is a bug in this crate. I will fix this when I have time, but as a possible workaround you could manually do the previous behaviour of looking up the section containing the symbol and use the section kind to determine what sort of symbol it is. (The fix will be to do essentially this.)

**Comment by philipc** [comment]
@erickt Could please test #116? I don't have a macOS system so I haven't tested it extensively.
