### ISSUE TITLE
macho_fixup_relocation incorrect

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#136]
https://github.com/gimli-rs/object/blob/24ba5e1304d2236bf64c6745e36b509e4b045d91/src/write/macho.rs#L70-L76

When `relocation.addend` will always be either `0` or `-4` afterwards, as the constant subtracted form `relocation.addend` contains `relocation.addend` itself. The match should have been written like:

```rust
let constant = match relocation.kind {
    RelocationKind::Relative
    | RelocationKind::GotRelative
    | RelocationKind::PltRelative => -4,
    _ => 0,
};
```

**Comment by philipc** [comment]
This is actually correct from what I can tell. `relocation.addend` has to be `0` or `-4` because Mach-O doesn't store addends in the relocation, so the addend has to match the valid addends here: https://github.com/gimli-rs/object/blob/24ba5e1304d2236bf64c6745e36b509e4b045d91/src/write/macho.rs#L400-L417

The rest of the addend isn't lost though, it is returned from this function and written to the data. Now maybe there is something wrong with the way that is written? Can you give more details on the problem you are having?

**Comment by bjorn3** [comment]
> Can you give more details on the problem you are having?

None. It just looked like a mistake.
