### ISSUE TITLE
MSVC debug unimplemented relocation kind: SectionIndex

### ISSUE THREAD

**Issue by jayvdb** [gimli-rs/object#156]
I've got a bit further with indygreg/PyOxidizer#183 by switching to the debug compiler flags `'/nologo', '/Od', '/MDd', '/Zi', '/W3', '/D_DEBUG'`, but then I encountered the following in `out_object.write()` on the MSVC objects.  This isnt a critical problem because these debug flags are rarely used.

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "unimplemented relocation Relocation { offset: 252, size: 16, kind: SectionIndex, encoding: Generic, symbol: SymbolId(164), addend: 0 }

It is a bit surprising that the backtrace doesnt show any `object` lines, but I guess that is because it is returning catching goblin errors and returning strings.

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "unimplemented relocation Relocation { offset: 252, size: 16, kind: SectionIndex, encoding: Generic, symbol: SymbolId(164), addend: 0 }"', src\libcore\result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
  21: std::rt::lang_start_internal::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:49
  22: std::panicking::try::do_call<closure-0,i32>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:296
  23: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  24: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:275
  25: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panic.rs:394
  26: std::rt::lang_start_internal
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:48
  27: std::rt::lang_start<()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  28: main
  29: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31: BaseThreadInitThunk
  32: RtlUserThreadStart
```

**Comment by philipc** [comment]
That'll be simple to fix, have a look at the [i386 support](https://github.com/gimli-rs/object/blob/27713e2f80376b555faee9ffa7dcb4ae8fbbea96/src/write/coff.rs#L345) and do the same thing for `IMAGE_REL_AMD64_SECTION` down below.

> It is a bit surprising that the backtrace doesnt show any object lines, but I guess that is because it is returning catching goblin errors and returning strings.

That's because the unwrap is in your code, not in goblin or object. It looks like your code isn't compiled with debuginfo either, since it has no line number information for main.

**Comment by jayvdb** [comment]
Ok, thanks, yea, I'll try this one over the w/e, it looks simple enough for me.

**Comment by jayvdb** [comment]
> That's because the unwrap is in your code, ..

I'd appreciate it if you could suggest improvements on https://github.com/indygreg/PyOxidizer/pull/183 (which is now green), especially how to have backtraces which include `goblin` origin of parse errors and `object` for write errors.

**Comment by philipc** [comment]
> how to have backtraces which include goblin origin of parse errors and object for write errors.

You can't without changing goblin and object.

By default, rust only generates backtraces at the point of the panic. By design, goblin and object return errors instead of panicking. The panic is occurring in your code where you unwrap, and so that is where the backtrace is generated.

goblin and object could be changed to manually generate a backtrace and include this in the errors they return, but this is not cheap, and I don't think it is appropriate for libraries like them. If the errors they are returning aren't informative enough, then we should improve those errors, rather than including backtraces. For the error in this issue, I had no trouble figuring out where it was occurring, but a possible improvement would be to include the binary format and architecture in the error that `object` returns.
