### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#194]
The `Object` traits currently use `Option` in places where they really should use `Result`.

**Comment by dtolnay** [comment]
Further, the things that currently use Result use it with a bad choice of E type:

- &amp;'static str: https://docs.rs/object/0.17.0/object/read/struct.File.html#method.parse
- String: https://docs.rs/object/0.17.0/object/write/struct.Object.html#method.write
- (): https://docs.rs/object/0.17.0/object/write/struct.Object.html#method.symbol_section_and_offset

This causes problems downstream because there is no Error impl for any of these types. See https://github.com/probe-rs/probe-rs/pull/143#discussion_r376802742 for one example where this is a problem.

**Comment by philipc** [comment]
What's bad about using `map_err` to convert to an error type you prefer?

**Comment by dtolnay** [comment]
@philipc it makes handling `object`'s errors noisy and annoying, whether the downstream crate is using a type erased error type *or* a custom one.

```rust
// type erased error type

use anyhow::Result;

pub fn demo() -> Result<()> {
    let data = std::fs::read("...")?; // okay
    let value: T = serde_json::from_str(...)?; // okay

    let object = object::File::parse(data)?; // DOESN'T WORK
}
```

```rust
// custom error type

use thiserror::Error;

#[derive(Error, Debug)]
pub enum Error {
    Io(#[from] std::io::Error),
    Json(#[from] serde_json::Error),
}

pub fn demo() -> Result<(), Error> {
    let data = std::fs::read("...")?; // okay
    let value: T = serde_json::from_str(...)?; // okay

    let object = object::File::parse(data)?; // DOESN'T WORK
    // (doesn't make sense to have a From<&'static str> impl)
}
```

**Comment by philipc** [comment]
@dtolnay So wrapping the `String` or `&'static str` in a newtype that implements `Error` would be a sufficient fix?

**Comment by dtolnay** [comment]
Yes that would work.
