### ISSUE TITLE
Expose error str in Error struct

### ISSUE THREAD

**Issue by schultetwin1** [gimli-rs/object#208]
My crate compiledfiles takes a dependency on the ability to inspect which error occurred in order to determine what to do new.

https://github.com/schultetwin1/compiledfiles/blob/0452bc2756ca01f31e4df06bbf38540ced37c1fb/src/lib.rs#L216-L222

Would you be open to making the internal `&str` in the `Error` struct public?

I'm new to Rust, so if this is not the proper way to do error handling let me know.

**Comment by philipc** [comment]
You definitely shouldn't be matching on the string. There is no guarantee that it will remain the same, even if we exposed it.

The current API of this crate doesn't allow you to distinguish between error reasons. A common way to distinguish between errors in Rust is to use an enum for the errors, but I've been reluctant to do that because the API that exposes is that any function can return any error, which is too broad and bloated. We could maybe add an error enum just for `File::parse` though.

Another option would be to split `File::parse` into two functions: one to detect the file format, and one to parse as a specific file format.

Also, reconsider whether distinguishing between these errors is required. File format detection can have both false positives and false negatives, so maybe you want to try all possible parsers regardless of the error.

**Comment by schultetwin1** [comment]
Thanks for all the great advice! Not matching on strings makes sense.

> Also, reconsider whether distinguishing between these errors is required. File format detection can have false positives, so maybe you want to try all possible parsers regardless of the error.

I think I'll take this approach for now. Closing this issue.
