### ISSUE TITLE
Allow write::Object to be written into pre-allocated buffer

### ISSUE THREAD

**Issue by yurydelendik** [gimli-rs/object#240]
The problem is `Object::write` allocates and writes everything into internal `BytesMut` and returns `Vec<u8>`. The issue is that it is not possible to create image without additional copy into target memory (e.g. to be protected with mmap).

Is it possible to introduce a method that will use a push type of writing of the image (e.g. `std::io::Write`)? It will be nice to get a total size of the image beforehand and pre-allocate target memory, similar to what is happening at `pub(crate) fn xxx_write()` methods.

**Comment by philipc** [comment]
Writing via a trait would be fine. I think pre-allocation should be a fallible method of that trait so that we don't complicate the size calculations. So it would need methods for:
- allocate
- write
- len (for debug asserts)
- (maybe other `BytesMut` methods, but I don't think we use more during the final object writing)

Note that another source of copies is the section data. Currently each section has a `Vec` that symbol data must be copied into. Avoiding copies for the section data too would be nice, but I think that will be more complicated. (e.g. the `objcopy` example should be able to mmap the input and copy directly to the output instead of going via a `Vec`).
