### ISSUE TITLE
Int underflow in objcopy.rs example

### ISSUE THREAD

**Issue by mrphrazer** [gimli-rs/object#257]
Heya,

there is an `attempt to subtract with overflow` in `examples/objcopy.rs:92:25` with the following sizes:

```
symbol address: 0x20
section address: 0x488920
```

The binary is attached. 

Best,

mrphrazer

[binary.zip](https://github.com/gimli-rs/object/files/5501702/binary.zip)

**Comment by philipc** [comment]
Hi, thanks for the report. This is kind of expected since you are running the example for an unsupported scenario. The objcopy example only supports object files, not executables, and it's unlikely to ever support executables. We could do better error handling for this case though.

What led you to try to run objcopy on this file? What are you trying to achieve? Currently, the objcopy example is mostly intended as a development tool for this crate. If you want something for production use then you'll want to use the objcopy from llvm or binutils instead.

**Comment by mrphrazer** [comment]
Hi,

thanks for the quick response! I am trying to evaluate different crates as a base for elf manipulations (adding/removing sections, segments etc.). `objcopy.rs` worked fine for my tested x86_64 binaries, so I thought this might be a bug due to a not so well-tested architecture.

**Comment by philipc** [comment]
Most testing has only been done with x86_64, so you're right that bugs in other architectures are more likely. We definitely don't support writing segments in objcopy.rs, so maybe you were only testing with x86_64 object files instead of executables.

This crate is probably not a good match for what you want to do. It does have the raw ELF structure definitions though, which might still be a useful basis.

**Comment by philipc** [comment]
Added `objcopy` check for supported file type in #352.
Added `write::elf::Writer` and `elfcopy` example in #350. Still no high level support for operations such as adding/removing sections, segments etc. Probably still missing some non x86-64 support.
