### ISSUE TITLE
Opinions on using a gimli::Reader-like abstraction, to parse large files in environments with constrained address space (e.g. wasm)?

### ISSUE THREAD

**Issue by mstange** [gimli-rs/object#269]
At the moment, `File::parse` [takes a reference to a slice of bytes](https://docs.rs/object/0.23.0/object/read/struct.File.html#method.parse). This requires the entire file to be "present" in memory (e.g. via mmap). That's usually fine.

However, when using `object` from WebAssembly (which is, admittedly, a use case that is both a bit niche and somewhat demanding), this API is problematic for the following reasons:

 - WebAssembly doesn't have support for mmap, so the entire file needs to be read into memory first, even if only small parts of it are needed.
 - WebAssembly (wasm32) is currently limited to a heap size of 2GB or 4GB, depending on the implementation.

For example, an optimized build of Firefox with debug info on Linux has a `libxul.so` which is 2.2GB big. [This means that WebAssembly code is currently unable to obtain any symbols from it.](https://bugzilla.mozilla.org/show_bug.cgi?id=1615066).

Would you be open to changing the `File::parse` API to take a `Reader` trait instead, similar to [how the `gimli` crate approaches this](https://docs.rs/gimli/0.23.0/gimli/read/trait.Reader.html)? This would allow reading just the parts of the file that are actually needed and would fix the wasm32 heap size problem. 

The two risks I can see are:

 - Possibly reduced performance, if the compiler is unable to inline-away the indirection in the simple wrap-a-slice Reader implementation.
 - Propagation of another template parameter for the reader through wide parts of the codebase (maybe?), which might lead to more complicated code and potentially longer compile times.

**Comment by philipc** [comment]
> Would you be open to changing the File::parse API to take a Reader trait instead, similar to how the gimli crate approaches this? 

I'm certainly open to the idea, but I think it will be a lot of work.

Do you know if anyone has used gimli's `Reader` to do this? I did add `Reader` for this purpose, but the potential use of it never happened.

`gimli` is slightly different in that very little of DWARF can be parsed with true zero copy, and so references in the parsing are limited to opaque things like strings or arrays of bytes where it is ok to represent them as another `Reader` instance rather than as a rust reference. Whereas this crate uses references for all of the headers too.

So the problem is that the `Reader` will need to allow conversion to a slice with a lifetime that is potentially larger than the lifetime of the `Reader` instance. That is, the lifetime will need to be a type parameter of the `Reader`, and converting the `Reader` to a slice will need to allocate somewhere such that the allocation has that lifetime (such as in an arena). A simple implementation of that might do a new allocation even for parts of the file that have already been read; not sure if that would matter.

**Comment by philipc** [comment]
Maybe generic associated types would help here. Something like:

```rust
trait Reader {
    type Ref<T>: Deref<Target=T>;
    fn read<T: Pod>(&mut self) -> Result<Ref<T>>;
}

impl<'data> Reader for &'data [u8] {
   type Ref<T> = &'data T;
   ...
}

impl<T: io::Read> Reader for T {
   type Ref<T> = Box<T>;
   ...
}

**Comment by mstange** [comment]
Thanks for the feedback!

**Comment by philipc** [comment]
Rough proof of concept for the arena idea in #278

**Comment by philipc** [comment]
@mstange Can you check if #278 works for your needs? It still needs some cleanup, but I think it's good enough for testing. The main outstanding issue is that it still completely reads each archive or Mach-O fat member, so better to check with ELF for now.

**Comment by mstange** [comment]
This is excellent, thank you so much! I will give this a try as soon as I can, hopefully before the end of the week.

**Comment by mstange** [comment]
I have started working on this. Nothing to report yet.

**Comment by mstange** [comment]
It works! It's exactly what I need. I did a naive implementation that doesn't do any caching, and it made getting the symbol table from a big ELF binary (libxul.so) 3x faster (5 seconds -> 1.7 seconds), because I no longer have to read and copy the entire file into JS and then WASM. I don't have a testcase that causes OOM at the moment, but I'm sure this solves the OOM problem, too.
The prototype is [in the `partial-file-reads` branch](https://github.com/mstange/profiler-get-symbols/compare/partial-file-reads?expand=1) but note that this repo doesn't include the Firefox JS code that actually ends up taking advantage of the partial file reads.

**Comment by philipc** [comment]
Great! Thanks for testing that. I'll get the PR cleaned up and merged when I can.

Does your test include reading DWARF? Just curious if `gimli`'s support for this works ok too.

**Comment by mstange** [comment]
Thank you so much!

No, I haven't covered the DWARF part yet. I'm planning to do that next.

**Comment by mstange** [comment]
I'm currently looking at the DWARF part. The first thing I'm stumbling over is the fact that I'm currently using `ObjectSection::uncompressed_data()` [here](https://github.com/mstange/profiler-get-symbols/blob/5c85d08bfdb05ca131855ce784c6e05c3f2f74d8/lib/src/dwarf.rs#L126), which reads the entire section data. I'll try to use `ObjectSection::file_range()` instead and see how far I can get with that. But this will mean that the code won't work with compressed dwarf data any more. For a proper solution, I think `CompressedData` will need to store a `ReadRef` instead of a slice, and also implement `Reader` itself.

**Comment by philipc** [comment]
I don't think `CompressedData` can implement `ReadRef` because compressed streams don't support seeking. Probably what we need is for `CompressedData` to include the file range (excluding the compression header) instead of the slice, and then you'll need to implement `gimli::Reader` for compressed data.

**Comment by mstange** [comment]
It could implement `ReadRef` for compressed streams the lazy way; by just reading the entire data and decompressing that. And for uncompressed streams it would forward along to the original `ReadRef`.

**Comment by philipc** [comment]
Why is it okay to read the entire section data for compressed data, but not for uncompressed data?

**Comment by mstange** [comment]
Oh, because it's not easy to do better for compressed data, unless you want to compress incrementally as needed... or maybe you have something in mind that I'm not seeing?
Oh, are you saying that `gimli::Reader` is more oriented towards incremental reading, whereas `ReadRef` is more oriented towards random access, and thus it would be easier to implement incremental decompression for `gimli::Reader`?

**Comment by philipc** [comment]
Ok that makes sense. I'm not keen on implementing `ReadRef` for `CompressedData`, but it seems that what we need is a way to avoid reading the entire section if the data isn't compressed (e.g a `compressed_file_range` method).

> it would be easier to implement incremental decompression for gimli::Reader?

I don't think so. DWARF has references to offsets within sections, so we would still need to seek.

**Comment by philipc** [comment]
I've done the cleanup on a new branch (#284), and added a `compressed_file_range` method.

**Comment by mstange** [comment]
I wrote a partial DWARF reading implementation, using the new `compressed_file_range` method, and it works: https://github.com/mstange/profiler-get-symbols/commit/b35e6a03c87a6cf7a0829f4bb53d25bc62323459
However, from quick testing it doesn't seem to allow much skipping of data. I haven't investigated very deeply.

**Comment by philipc** [comment]
I haven't looked in detail, but I doubt you want to do this:
`impl<'data, T: ReadRef<'data>> Reader for EndianRangeReadRef<'data, T> {`
because the reading expectations of `object::ReadRef` and `gimli::Reader` are too different. `object::ReadRef` tends to read a small number of largish blocks (file header, section table, symbol table, string table, section data), whereas `gimli::Reader` tends to be a large number of small reads within one section. In particular, if the `object::ReadRef` is allocating for each read, then that's going to be a lot of small allocations, most of which will never be used again. The point of `object::ReadRef` is to allow returning references to data, but `gimli::Reader` doesn't use that ability.

Returning references may have been an alternative to use for reading things like strings, but we don't currently do that. Instead, we use `gimli::Reader::split` to get a new `gimli::Reader` instance which we store and then read again later with `gimli::Reader::to_slice` or `gimli::Reader::to_string`. There may be room for improving how we handle strings, but I think it will be by returning the `Cow` immediately instead of delaying it until a later `to_slice/to_string` call.

So instead I think the `gimli::Reader` implementation should be more like `std::io::BufReader` than like `object::ReadCache`.

**Comment by mstange** [comment]
That totally makes sense, thanks a lot for the additional context.

**Comment by philipc** [comment]
I started on doing a non-mmap example for gimli at https://github.com/philipc/gimli/commit/1e4ee29d4b7d0b5a787cbe4d7125997399ae1b88. It's a bit rough still (doesn't handle compressed sections).
