### ISSUE TITLE
Object trait could expose platform specific things using raw_* methods

### ISSUE THREAD

**Issue by dvc94ch** [gimli-rs/object#275]
At the moment it seems I can parse an elf file as either a `File` which implements `Object` or a `FileHeader` which does not.

**Comment by philipc** [comment]
Can you give an example of a `raw_*` method?

**Comment by dvc94ch** [comment]
`raw_header` for example could return the elf `FileHeader`. alternatively `FileHeader` could implement `Object` so that I can pass it to stuff that expects an `Object`.

**Comment by philipc** [comment]
> raw_header for example could return the elf FileHeader

The `Object::raw_header` couldn't return an elf `FileHeader` directly, because the signature of `Object::raw_header` must be the same for all implementations, and you wouldn't want it to return the elf `FileHeader` for the Mach-O implementation.

> alternatively FileHeader could implement Object so that I can pass it to stuff that expects an Object

This isn't possible because the implementation of `Object` requires more information than is in `FileHeader`.

> Or add raw_header to ElfFile (which implements Object and has access to the FileHeader)

Yes, this is certainly something I've considered doing. The main question is: if you're writing code that is specific to ELF anyway, does the `Object` trait really provide much benefit over using the ELF structs directly? (Maybe it does, I'm unsure.)

**Comment by dvc94ch** [comment]
well `addr2line` expects an `Object` for example, and `Object` seems to do everything I need except getting the dynamic libraries.

**Comment by philipc** [comment]
Ok, sounds good then.
