### ISSUE TITLE
`macho_write` imposes an erroneous limit on section name length

### ISSUE THREAD

**Issue by eggyal** [gimli-rs/object#289]
Hit a panic on this line

https://github.com/gimli-rs/object/blob/569c33d80f5f47f2ef9fb21aeccabd64ae462c25/src/write/macho.rs#L371

because my `section.name` was larger than the `sectname` buffer (it's `__DATA,__mod_init_func`, i.e. the section reserved for module initialisation functions).

I don't know what the actual maximum section name size is in MachO, but a 16-byte buffer definitely isn't enough.  At very least, `Object::add_section` should *document* this limit (and should perhaps also be fallible, returning an error if the limit is exceeded?).

**Comment by philipc** [comment]
The limit is definitely 16 bytes, e.g. the following structure comes directly from macos headers:
https://github.com/gimli-rs/object/blob/b353d126f31188f5b1f5c9e78a3051e05d9a06c7/src/macho.rs#L808

The section name is `__mod_init_func`. The segment name is `__DATA`. You need to set these separately.

> At very least, Object::add_section should document this limit (and should perhaps also be fallible, returning an error if the limit is exceeded?).

The minimum should be that `Object::write` returns an error instead of panicking. It's fine to document things like this if needed, but the implicit assumption is that you must follow all of the requirements of the file format you are writing, and there are too many of those for this crate to consider documenting them all.

**Comment by eggyal** [comment]
Okay, thanks.  Looks like the issue is in rustc_codegen_cranelift then, as that's where the `Object` is being created.  Will file an issue over there.
