### ISSUE TITLE
The addresses for PE exports would be more useful to me if they didn't include the image base address

### ISSUE THREAD

**Issue by mstange** [gimli-rs/object#314]
`PeFile::exports` currently adds the image base address to the va before returning the export address:
https://github.com/gimli-rs/object/blob/832f5277a0774de18f84e7c27401f974e4b6a064/src/read/pe/file.rs#L327-L330

Is this the right thing to do?

If the returned addresses were *relative* to the image base (i.e. didn't include the image base), it seems like they'd be in the same space as the PDB's "rva" addresses. This address space would be more useful for my use case, which is looking up addresses for a profiler.

In `profiler-get-symbols` I have a path which falls back to using the PE file exports, and I currently subtract out the image base address manually:
https://github.com/mstange/profiler-get-symbols/blob/ee43039a9e85886dfcd19e4fa2717d3b2a29fab0/lib/src/windows/mod.rs#L96-L106

I was using goblin for this before, which does not seem to include the image base in [`goblin::pe::export::Export::rva`](https://docs.rs/goblin/0.4.1/goblin/pe/export/struct.Export.html#structfield.rva).

**Comment by mstange** [comment]
Alternatively, maybe this could be a feature request instead: "Provide easy access to the base address".

I have to do a very similar translation for ELF/mach-o binaries, where my addresses are relative to the vmaddr of the `__TEXT` segment. Here's where I subtract the base address out:
https://github.com/mstange/profiler-get-symbols/blob/ee43039a9e85886dfcd19e4fa2717d3b2a29fab0/lib/src/shared.rs#L212-L228

Maybe it would make sense to provide both of these addresses behind a shared `Object` API?

**Comment by philipc** [comment]
We also add the image base for symbol addresses:
https://github.com/gimli-rs/object/blob/832f5277a0774de18f84e7c27401f974e4b6a064/src/read/coff/symbol.rs#L336-L338
https://github.com/gimli-rs/object/blob/832f5277a0774de18f84e7c27401f974e4b6a064/src/read/coff/symbol.rs#L200

and I did this change because backtrace needed to do this (even though backtrace isn't using this code):
https://github.com/rust-lang/backtrace-rs/blob/975665054431f6bb4987241d3dd44cf30bc45d30/src/symbolize/gimli/coff.rs#L64

and I haven't checked but I expect that this is required for the example code in the `addr2line` crate when using mingw.

We're not adding it for section addresses, so at least one of these is probably wrong.
https://github.com/gimli-rs/object/blob/832f5277a0774de18f84e7c27401f974e4b6a064/src/read/coff/section.rs#L120

It seems correct for these to be consistent at least within PE, and additionally it needs to be possible to write code that also works for ELF/Mach-O without change.

> Maybe it would make sense to provide both of these addresses behind a shared Object method?

We need to provide something, but I'm not sure what. My gut feeling is that we should leave ELF/Mach-O unchanged, and return RVAs for PE, and document that all addresses are relative to the value returned by `Object::image_base`, which would return 0 for ELF/Mach-O. I'm open to suggestions on what is best though.

**Comment by mstange** [comment]
Thanks for the background. Your suggestion at the end sounds good to me. I don't know enough about the subject matter to have a more well-reasoned opinion.
