### ISSUE TITLE
High level write for PE files

### ISSUE THREAD

**Issue by nickbclifford** [gimli-rs/object#373]
I'm having a lot of trouble wrapping my head around the PE format, especially when dealing with RVAs and alignment, and I would really appreciate if PE was supported with the `write::Object` APIs since I'm already using this crate for reading.

**Comment by philipc** [comment]
`write::Object` will never support PE, because `write::Object` is designed to only support object file formats, not executable file formats.

What we can do is add `write::pe::Writer` which will be the equivalent of `write::elf::Writer`.

How are you generating the data that will be placed in the PE? Is it coming from an existing PE file?

**Comment by nickbclifford** [comment]
Got it, thanks for the clarification!

I will be generating the data by hand, as I'm writing an experimental .NET compiler, and have reached the point where I need to write to file.

**Comment by philipc** [comment]
Will this be a normal .NET assembly file (https://docs.microsoft.com/en-us/dotnet/standard/assembly/file-format), meaning you only need to support the format described in ECMA 335?

**Comment by nickbclifford** [comment]
Correct, I'm not doing anything outside that spec.

**Comment by philipc** [comment]
See #382 for an initial PE writer. This handles the headers etc, but you need to provide the section data yourself. Let me know what's missing.

It's possible you need something for writing the import table, but given that I think you'll only have 1 import, it's maybe not so hard for you to do a simple fixed size import table instead of needing something fully general.

**Comment by nickbclifford** [comment]
Wow, this looks incredible! Thank you so much, you're a saint! 

I don't immediately see anything that's missing, and yes, I agree, I don't think a full import table abstraction is necessary.
