### ISSUE TITLE
Implement relocations

### ISSUE THREAD

**Issue by philipc** [gimli-rs/object#4]
If there is a `.rela.debug_info` section, then those relocations need to be applied before gimli can parse `.debug_info`. See `atefail/ig_server` from the libdwarf regression tests for an example.

**Comment by m4b** [comment]
I would be very interested in starting a crate with ppl that given a list of relocations and some bytes, relocates them. Goblin already parses the relocations for you for ELF; have to look at Mach relocations again (they are vastly simpler and engineered better, but that's unsurprising since Apple are masters of the binary 🤓 ), and add a new field to goblin Mach parser for relocations.

@philipc @fitzgen are either of you (or anyone else) interested in starting working on a generic crate like this?

**Comment by philipc** [comment]
It's something I want to work on eventually, but I don't have time for it right now. Probably want the API to work on individual relocations, rather than requiring a list, so that we can support streaming the data.

**Comment by m4b** [comment]
Sure of course we'd expose a function per relocation. But that's getting into lib details :)

I don't really have the time either but I'd still like to work on it, ideally not by myself
