### ISSUE TITLE
All symbols for macos executable has zero size

### ISSUE THREAD

**Issue by RazrFalcon** [gimli-rs/object#44]
Here is a [code example](https://github.com/RazrFalcon/cargo-bloat/blob/e8c751b18c1dc84c769a73b50d0c6716678ec86d/src/main.rs#L144).

I assume that the problem is in the mach-o parser. Or is it a valid behavior?

**Comment by philipc** [comment]
Yeah, mach-o symbols don't include a size. If you need sizes then you can use `Object::symbol_map` and `SymbolMap::symbols`.

**Comment by philipc** [comment]
Also note that you won't get symbols on Windows... we need to do something to find the PDB file and then implement object support for PDB files.

**Comment by RazrFalcon** [comment]
Thanks. It works.

Does `symbol_map` contains a different values from `symbols`? In my tests result are the same. But if they the same - why we need two methods?

I have zero knowledge about ELF/mach-o, so I don't want to miss something important.

**Comment by philipc** [comment]
The ELF file format includes symbol sizes, the Mach-O file format does not. `symbols` gives you the values from the file format. `symbol_map` gives you the same symbols, but it also does some extra processing for Mach-O to guess what the size is. `symbol_map` also sorts the symbols by address, so that you can do binary searches for an address. We have separate methods so that you can choose to avoid that processing (either because you want to see exactly what is in the file, or because you don't need the size so it's a bit faster).

**Comment by RazrFalcon** [comment]
Thanks a lot! Especially for the library.
