### ISSUE TITLE
Unsupported file format

### ISSUE THREAD

**Issue by zhangchao1** [gimli-rs/object#454]
system:macOS
object library version:0.29.0
open local dSYM file occur error:Unsupported file format,i find the file has two architecture,(armv7,arm64),another file only one 
architecture can work well

**Comment by philipc** [comment]
Does the `objdump` example work on the file?

This sounds like `FileKind::parse` is returning `FileKind::MachOFat32` or `FileKind::MachOFat64`, and `File::parse` is failing because it does not support that. This is expected behaviour: you need to use `FatHeader::parse_arch32` or `FatHeader::parse_arch64` for these files, since they contain multiple architectures. The [code in the objdump example](https://github.com/gimli-rs/object/blob/40d77b2164145219e37778328eca6f070e4a8983/crates/examples/src/objdump.rs#L31-L50) shows how you can parse these files.

**Comment by zhangchao1** [comment]
sorry,in object version 0.29.0 ,arch.architecture() this method has no exist

**Comment by philipc** [comment]
The objdump code that I linked is version 0.29.0, so it does exist. The `architecture` method is from the [`FatArch` trait](https://docs.rs/object/0.29.0/object/read/macho/trait.FatArch.html#method.architecture). You'll need to use that trait, as [done in the objdump example](https://github.com/gimli-rs/object/blob/40d77b2164145219e37778328eca6f070e4a8983/crates/examples/src/objdump.rs#L2).
