### ISSUE TITLE
round_trip::elf::symtab_shndx fails on big endian

### ISSUE THREAD

**Issue by plugwash** [gimli-rs/object#456]
round_trip::elf::symtab_shndx fails on big endian, I initially noticed this on a Debian CI test on s390x, but I also reproduced it manually with the latest version of the gimli-rs git repository on s390x, ppc64 and powerpc. The rustc used in all cases was the one from Debian sid.

    ---- round_trip::elf::symtab_shndx stdout ----
    thread 'round_trip::elf::symtab_shndx' panicked at 'assertion failed: `(left == right)`
      left: `Section(SectionIndex(16711680))`,
     right: `Section(SectionIndex(65280))`', tests/round_trip/elf.rs:38:9

I bisected and it seems the symtab_shndx test started failing with commit 6b8c39cbdc73f24e76d080d1f41a6c5fb3f37624 though other round trip tests that do not fail with the latest version were failing before that.

**Comment by philipc** [comment]
Thanks for the report. The bisected commit is when the check was added; it seems to have always been broken. It should be fixed by #458.

**Comment by plugwash** [comment]
Thanks.

You mention this is a breaking change, that would seem to suggest against including it as a distribution patch, do you have any idea when this might be included in a release?

**Comment by philipc** [comment]
I'm not familiar with how the distribution package is used. If this is only used to build a fixed set of packages within the distribution, then you'd be able to patch any of those if the breaking change affects them. There may not even be any packages that use the affected APIs.

It hasn't been long since the last release with breaking changes, so I prefer to wait longer before doing that.
