### ISSUE TITLE
Conversion from `read::File` to `write::Object`?

### ISSUE THREAD

**Issue by mjhouse** [gimli-rs/object#468]
I'm trying to build some binary analysis/cyber security tools using this library (ELF format, specifically) and it would be useful if I could read a shared library, modify it, and then write it back out to a new location. Is this possible currently?

**Comment by mjhouse** [comment]
Ok, that seems to work, but a `cmp` on the two files shows significant differences between them, and I'm not sure why.

**Comment by bjorn3** [comment]
Maybe segments are reordered compared to the original. This should be harmless. Does the library still work after running the copy example that you used on it? (of course try this only on a non-malicious library. it the file you tested it is malicious you could try for example a system library)

**Comment by mjhouse** [comment]
It works. Looks like it's partially a reordering, but some of it looks like the instructions have changed- maybe objdump is interpreting the assembly differently for the two versions, for some reason. Apparently the changes are harmless, though- it's a very simple test library built specifically for testing.

**Comment by bjorn3** [comment]
Which of the examples are you using? The elfcopy example should copy all relocations verbatim, while the objcopy example interprets the elf relocation into a generic format and then turns it into an elf relocation again. This roundtrip is lossy in some cases due to unimplemented support for some relocations I believe.

**Comment by mjhouse** [comment]
I'm working with the elfcopy example.

**Comment by bjorn3** [comment]
No clue what is going on then.

**Comment by mjhouse** [comment]
No worries. I'll keep working with the elfcopy example. Thanks a lot for the help, man.

**Comment by philipc** [comment]
> Looks like it's partially a reordering, but some of it looks like the instructions have changed- maybe objdump is interpreting the assembly differently for the two versions, for some reason.

There shouldn't be any changes to instructions.

> Changes are mostly in the .dynstr and .dynamic sections.

Changes in these sections are expected because it must recreate the `.dynstr` section in case your modifications require strings to be added or removed, and string table offsets in the `.dynamic` section may change as a result of that.

I won't be surprised if `elfcopy` doesn't handle everything, but please create issues if you do encounter anything.

**Comment by mjhouse** [comment]
@philipc If I see anything, I'll let you know. I know it's a long shot, but I don't suppose there are any docs explaining how to remove a single function during the copy, is there?

**Comment by bjorn3** [comment]
For an already linked library, there isn't really any way to do so other than to disassemble, remove the function and assemble it again. After linking the code section contains relative offsets to other parts of the code section and to the data section everywhere. If you want to cut a part of it away, you have to update every reference with the new addresses.
