### ISSUE TITLE
Baremetal binary backend

### ISSUE THREAD

**Issue by roblabla** [gimli-rs/object#65]
I'm currently working on symbolication on an odd platform (homebrew on the Nintendo Switch), which doesn't use ELF or Mach (or anything standard for that matter). I was wondering if it'd be a good idea to implement a "dumb" backend that hardcodes common section names, and finds them with linker symbols. For instance, `__debug_abbrev_start`, `__dynamic_start`, etc... With weak linkage, we could get something that works pretty well, I think.

So we would create a `BaremetalObject` (unit?) struct that implements `Object`.

Would such a PR get accepted ?

**Comment by philipc** [comment]
Probably? As long as it doesn't complicate the rest of the crate. You mainly want the `sections` or `sections_data_by_name` methods?

I'm not sure how much it would gain you though. If you're only wanting to use the `addr2line` crate, I don't think there would be much boilerplate involved in passing sections to [`Context::from_sections`](https://github.com/gimli-rs/addr2line/blob/ca23d988c121ac4fad047085223268e98726aa2d/src/lib.rs#L161) instead of using this crate. We can change the `object` dependency in `addr2line` to be optional.

**Comment by roblabla** [comment]
Hmm, yeah that's probably more reasonable.

My end-goal was to get backtrace-rs working in an embedded context, in order to use it in a custom libstd I'm working on, to report backtraces. But taking a closer look, there are many things that simply won't work (I'd also need some way to "fix" findshlibs, and I'd need to make backtrace-rs [not mmap the so files](https://github.com/alexcrichton/backtrace-rs/blob/aaddd2a/src/symbolize/gimli.rs#L30). I'm probably better off using addr2line and gimli directly instead.
