### ISSUE TITLE
`zerocopy` support

### ISSUE THREAD

**Issue by tbu-** [gimli-rs/object#687]
I'm already using Google's [`zerocopy`](https://github.com/google/zerocopy) in my crate and want to start using `object`. Would a PR adding support for `zerocopy` bee accepted? Theoretically, the whole `pod` module could also be replaced by it.

**Comment by bjorn3** [comment]
The zerocopy crate can't be used as dependency of libstd as it doesn't have the rustc-dep-of-std hack. Libstd depends on object through the backtrace crate. As any zerocopy integration has to be optional.

**Comment by tbu-** [comment]
Some information on the rustc-dep-of-std hack, since I didn't know about it before: https://github.com/rust-lang/wg-cargo-std-aware/issues/51.

**Comment by philipc** [comment]
The `pod` module is small, does exactly what this crate needs, and can't be replaced (as bjorn3 says).

Can you give an example of what adding `zerocopy` support would enable you to do that you can't easily do without it? Can you give a reason for choosing `zerocopy` instead of another option (`bytemuck` is the most common alternative)?

I have looked at both `zerocopy` and `bytemuck` in the past and my impression was they don't gain us anything. In particular, we can't use their derive support because they don't support type parameters (needed for endianness).

**Comment by tbu-** [comment]
> we can't use their derive support because they don't support type parameters (needed for endianness).

Ah, that sucks. :(

> Can you give an example of what adding `zerocopy` support would enable you to do that you can't easily do without it?

Using the crate's structs in my own zero-copy-derived structs, with safety guaranteed by zerocopy.

> Can you give a reason for choosing `zerocopy` instead of another option (`bytemuck` is the most common alternative)?

I wasn't aware of `bytemuck`, interesting. It doesn't seem to have endianness support though/

**Comment by philipc** [comment]
> Using the crate's structs in my own zero-copy-derived structs, with safety guaranteed by zerocopy.

Ok, but the safety can't be guaranteed because the derive doesn't support this crate's structs (unless it has changed since I last looked). So is there still any value to this?

> I wasn't aware of bytemuck, interesting. It doesn't seem to have endianness support though

We would still need to define our own endianness types, whether we use `zerocopy` or `bytemuck`, since `zerocopy` doesn't have an equivalent of [`Endianness`](https://docs.rs/object/latest/object/endian/enum.Endianness.html).

**Comment by tbu-** [comment]
> Ok, but the safety can't be guaranteed because the derive doesn't support this crate's structs (unless it has changed since I last looked). So is there still any value to this?

The safety can be guaranteed for my *own crate* when I use zerocopy, since I don't use generic endianness there.





> We would still need to define our own endianness types, whether we use `zerocopy` or `bytemuck`, since `zerocopy` doesn't have an equivalent of [`Endianness`](https://docs.rs/object/latest/object/endian/enum.Endianness.html).

Ah, the `Endianness` type is some kind of run-time dynamic endianness?

**Comment by philipc** [comment]
> The safety can be guaranteed for my own crate when I use zerocopy, since I don't use generic endianness there.

So you're not using this crate's structs in your own zero-copy-derived structs then. To be clear, it's going to be a high bar to add support here. You'll need to give a code example of what it allows you to do. Simply avoiding importing another trait in your crate isn't enough.

> Ah, the Endianness type is some kind of run-time dynamic endianness?

Yes.

**Comment by tbu-** [comment]
> > The safety can be guaranteed for my own crate when I use zerocopy, since I don't use generic endianness there.
> 
> So you're not using this crate's structs in your own zero-copy-derived structs then.

Yes, I currently can't derive zerocopy's traits because this crate doesn't implement them on its types. This is basically the reason for this feature request.

> You'll need to give a code example of what it allows you to do. Simply avoiding importing another trait in your crate isn't enough.

Makes sense. Since I don't have a finished crate, I'll close this feature request. I'll come back if I ever finish this project.

**Comment by bjorn3** [comment]
Also object can't make use of the zerocopy derive macros anyway as libstd can't (directly or indirectly) depend on any proc macro without breaking cross compilation support.
