### ISSUE TITLE
Support other platforms

### ISSUE THREAD

**Issue by jrmuizel** [gimli-rs/object#8]
It would be nice if object wasn't limited to supporting only the target platform

**Comment by jrmuizel** [comment]
It looks like https://github.com/m4b/goblin does a decent job of this already.

**Comment by fitzgen** [comment]
The `object` crate supports using ELF on targets that don't use it natively. For Mach-O, we bind to the system object parser, which isn't available on other targets.

I would love to deprecate `object` for `goblin`, but the Mach-O support isn't quite ready yet (nor do I have the personal cycles to help get it there atm).

**Comment by philipc** [comment]
I'm in the process of changing `object` to use `goblin`, since I still want something that gives a unified interface to both ELF and Mach-O.

@fitzgen do you have any specific issues with the Mach-O support in goblin that I should check are handled?

**Comment by fitzgen** [comment]
> I'm in the process of changing object to use goblin, since I still want something that gives a unified interface to both ELF and Mach-O.

I wonder if @m4b would be interested in adding such an interface to `goblin` directly? Seems like `object` wouldn't need to exist at all at that point.

> @fitzgen do you have any specific issues with the Mach-O support in goblin that I should check are handled?

I just remember support being described as incomplete. If its enough to implement `object`'s existing trait without bugs, then it should be A-OK.

**Comment by m4b** [comment]
So just released 0.10.0 on crates.io and support for the various 32/64 bit binary formats is pretty mature imho, with zero-copy, lifetime based parsing where appropriate.  There is a toplevel `goblin::Object` which you access via `goblin::parse`, which takes a `&[u8]` and returns the `goblin::Object`, e.g.:

```rust
let path = Path::new(arg.as_str());
let mut fd = File::open(path)?;
let mut buffer = Vec::new();
fd.read_to_end(&mut buffer)?;
match goblin::parse(&buffer)? {
    Object::Elf(elf) => {
        println!("elf: {:#?}", &elf);
    },
    Object::PE(pe) => {
        println!("pe: {:#?}", &pe);
    },
    Object::Mach(mach) => {
        println!("mach: {:#?}", &mach);
    },
    Object::Archive(archive) => {
        println!("archive: {:#?}", &archive);
    },
    Object::Unknown(magic) => { println!("unknown magic: {:#x}", magic) }
}
```

On hindsight I should probably add a `Object::new` ;) but I forgot; next release.

Anyway, it's pretty simple at this point, and each of the Elf, Mach, Pe, etc., structs have their various documentation, but many of the fields I tried to keep the same when appropriate.  There's still various work to do of course, but they're getting more or less rounded out I think. Panopticon uses it as the loader and it seems to function quite well; I haven't done much with sections though since they're usually strippable and hence no necessarily worthwhile in binary analysis, but they should all be supported where appropriate in the formats.

Let me know if you have any questions.

Is there a particular reason for adding the interface to goblin - e.g., why couldn't `object` impl it for the various goblin binary structs? This way consumers of `object` wouldn't have to change to `goblin`, but the implementation would simply swap out iiuc.

**Comment by philipc** [comment]
#9 converts `object` to use `goblin`. I didn't use `goblin::Object::parse` because I had already written code to do basically the same thing, and I didn't want to extend `object` to also handle PE and archives.

I do agree with @fitzgen that it would be nicer to deprecate `object` and use `goblin` directly. #9 is just to make it easier for current users to gain the cross platform benefits of `goblin` without needing to change existing code immediately.

Does it make sense to add more methods to `goblin::Object` that provide the common functionality? (ie for our use, we want to determine if the file is little endian, and look up the data for named DWARF sections).

**Comment by m4b** [comment]
It might make sense. It could also be awkward. Little endianness only applies to technically 3-5 objects goblin understands (archives and Mach multi arch binaries not being applicable). 

Sections are applicable to at least ELF and Mach (but one is optional and the other not really), and iirc the PE equivalent are the data directories (also optional); but I don't know if it stores dwarf info there. In fact I don't know if PE supports dwarf at all, don't known much about the PE debugging story besides the mainstream (MS) compiler using the primarily unspecified PDB system. 

So would have to decide on what the appropriate return value for these methods on the Object enum would be. 

Otherwise shouldn't be too hard I think, if it's minor stuff like this. But if it's starting to implement a complicated section based debugging grabbing API, I'm hesitant to add that as it's just one more thing for me to maintain, and potentially seems better suited for a downstream client crate to implement a more robust specific implementation on the basic structs that goblin provides. 

Anyway definitely open to the idea; feel free to open an issue in goblin and we can discuss what exactly you want/need

**Comment by fitzgen** [comment]
> Otherwise shouldn't be too hard I think, if it's minor stuff like this. But if it's starting to implement a complicated section based debugging grabbing API, I'm hesitant to add that as it's just one more thing for me to maintain, and potentially seems better suited for a downstream client crate to implement a more robust specific implementation on the basic structs that goblin provides.

Take a look at the trait we have now: https://docs.rs/object/0.3.0/object/trait.Object.html

This is basically the API surface we would like to add. I think it is fairly minor additions.

> So would have to decide on what the appropriate return value for these methods on the Object enum would be.

Right now we have a signature like `fn get_section(&self, name: &str) -> Option<&[u8>`. I think in the cases where there aren't sections, we can always return `None` and document this behavior.

DWARF can be embedded into PE/COFF, and `rustc`/`clang`/`llvm` often do this IIUC. I don't know the details however, and as MS adds more documentation (specifically because they want `llvm`/`clang` generating their debugging info) it may become more rare.

I think we should punt on it until someone actually wants to use them together, and can dive in deeper.
